format_version: 5
pipelines:
    build:
      group: sl_prog101
      materials:
        repo:
          git: git@bitbucket.org:at12-group-01/sl_prog101.git
          branch: master
        mydependency:
          pipeline: test
          stage: Test
          ignore_for_scheduling: false
        artifact_assemble:
          pipeline: assemble
          stage: Assemble
          ignore_for_scheduling: false
      secure_variables:
        ARTIFACTORY_USER: "AES:BpMCugkB6TVf1/EPlW2hKw==:Gp4NjDNReILmUCkMsoVCCw=="
        ARTIFACTORY_PASSWORD: "AES:O4JeQke0tCv3O5KA5LO7eg==:scBPObfEE/fYVY3s9cku0w=="
      stages:
        - build:
            jobs:
              publish:
                tasks:
                  - fetch:
                      pipeline: assemble
                      stage: Assemble
                      job: run
                      source: assemble/build/
                      destination: "./"
                  - exec:
                      command: ./gradlew
                      arguments:
                        - "build"
                        - "artifactoryPublish"
                        - "--console"
                        - "verbose"
                        - "-P artifactory_user=$ARTIFACTORY_USER"
                        - "-P artifactory_password=$ARTIFACTORY_PASSWORD"
