format_version: 5
pipelines:
    test:
      group: sl_prog101
      materials:
        repo:
          git: git@bitbucket.org:sloza/sl_prog101.git
          branch: gocd
        mydependency:
          pipeline: assemble
          stage: Assemble
          ignore_for_scheduling: false
      stages:
        - Test:
            jobs:
              run:
                tasks:
                  - exec:
                      command: ./gradlew
                      arguments:
                        - "test"
                artifacts:
                  - test:
                      source: build/test-results/test/*.xml
                      destination: xml
                  - test:
                      source: build/reports/tests/test/*
                      destination: html